# Generated by Django 5.2.4 on 2025-08-23 12:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_work_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('standard_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('standard_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('late_threshold_minutes', models.IntegerField(default=15)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('break_duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave')], default='Present', max_length=20)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('break_duration', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_hours_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('punctuality_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='employees.employee')),
            ],
            options={
                'ordering': ['-month', 'employee__first_name'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
